### ISSUE TITLE
 url not valid

### ISSUE THREAD

**Issue by devhammam95** [neodynamic/WebClientPrintPHP4-Sample#2]
have this error any help
WebClientPrint Error: The URL http://localhost/test-printing/PrintESCPOSController.php?clientPrint&printerName=HP%2520LaserJet%2520Professional%2520P1102 is not valid (Status Code: 404). The print job process was cancelled.

**Comment by neodynamic** [comment]
The error states that the URL  http://localhost/test-printing/PrintESCPOSController.php does not exist (404 HTTP Error)... is that correct?

**Comment by shibilababy** [comment]
WebClientPrint Error: The URL PrintESCPOSController?clientPrint&useDefaultPrinter=checked&printerName=RP80 Printer is not valid (Status Code: 200). The print job process was cancelled.
please help
