### ISSUE TITLE
WebClientPrint Error

### ISSUE THREAD

**Issue by celalk** [neodynamic/WebClientPrintPHP4-Sample#4]
Please, somebody can help me? Whatis solution for this problemme

WebClientPrint Error: The URL http://192.168.1.242/printtest/PrintEPLController.php?hrkid=9584&clientPrint&useDefaultPrinter=checked&printerName=undefined is not valid (Status Code: 200). The print job process was cancelled.

Response Cookies: 

Headers received from that URL:

"HTTP/1.1 200 OK","Content-Type: application/octet-stream","Content-Encoding: gzip","Vary: Accept-Encoding","Server: Microsoft-IIS/8.5","X-Powered-By: PHP/7.3.12","X-Powered-By: ASP.NET","Date: Tue, 02 Mar 2021 14:13:34 GMT","Content-Length: 785"

Content received from that URL:

﻿cpj?

**Comment by neodynamic** [comment]
Contact our team at https://neodynamic.com/support
